export const cases = {
  ADD_PRODUCT_TO_CART_BUTTON_HOME: "ADD_PRODUCT_TO_CART_BUTTON_HOME",
  REMOVE_PRODUCT_FROM_CART_BUTTON_CART: "REMOVE_PRODUCT_FROM_CART_BUTTON_CART",

  ADD_PRODUCT_TO_CART_BUTTON_SINGLE_PRODUCT:
    "ADD_PRODUCT_TO_CART_BUTTON_SINGLE_PRODUCT",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  CHANGE_FORM_VALIDATION: "CHANGE_FORM_VALIDATION",
  CHANGE_FORM_VALIDATION_BY_LOGIN_INPUTS: "CHANGE_FORM_VALIDATION_BY_LOGIN_INPUTS"
};
